tasks:
  - before: |
      export FLASK_APP=flaskr
      export FLASK_ENV=development
    init: |
      pip install -e .
      flask init-db
    command: |
      flask run

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
